### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by mbenten** [danni/python-pkcs11#55]
Hello all,

I tried to install the python-pkcs11 package into my `Anaconda 3` environment, but was not able to finalize this task.  I did make some progress with all the errors, I was facing, but got stuck at a certain point.

I am using Anaconda 3 as 64 bit version on a Windows 7 that is installed on a HP laptop with an i5 CPU.

Due to the fact that the compilation failed, I installed first the recommended Visual Studio Builder Tools, but this did not help, so that I at the end installed the full visual studio 2019 environment. 

But even with this the installation fails with the error:
> pkcs11\_loader.c(596): fatal error C1083: Datei (Include) kann nicht ge"ffnet werden: "dlfcn.h": No such file or directory

Attached you will find what the console-output told me during the installation in verbose mode.

[pip-installation-output.txt](https://github.com/danni/python-pkcs11/files/3239105/pip-installation-output.txt)

Could you please tell me, how I can solve the issue, so that the package will be installed?

Kind regards,
Manfred

**Comment by danni** [comment]
Hi @mbenten, try installing master, this should include the Windows fixes you need. Let me know.

**Comment by mbenten** [comment]
Hi @danni,

thank you for the fast answer, but I don't know exactly what you mean with **installing master**?

Is this an anaconda or a python or a visual studio or a windows installation.
I tried o use `conda install master` and `pip install master`, but both mechanisms did not find packages.
I tried to search with google for some combinations of "windows 7 install mastar pyton anacona", but the results were also not helping.

Could you please navigate me to propper place from where I can get the package/installer?

Thank you,
Manfred

**Comment by danni** [comment]
I mean install the master branch of this package. Check out this Stack Overflow:  

https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch

**Comment by mbenten** [comment]
Hi @danni,

thank you for this answer and the link.  That helped indeed.
I was able to installed the package on both python 2.7.12 and python 3.7.3 in my anaconda environment by using the following command:

`pip install git+https://github.com/danni/python-pkcs11`

Can you already assess, why it did not run by just using the command:
`pip install python-pkcs11`

Will this question drive some fixes to the code?

Thanks again for the support.

I think that the question itself can be closed since I was able to install...

Kind regards from Hamburg in Germany,
Manfred

**Comment by danni** [comment]
Hi @mbenten,

It definitely will not function in Python 2.7. If it builds at all, it will crash upon execution. This code has not been written to function in Python 2.7.

The version you installed originally did not work because of Windows compatibility errors, these are only fixed in master and not the release version.

**Comment by edkek** [comment]
I just came across this issue today, why is this issue closed if `pip install python-pkcs11` is still broken on Windows?
